### ISSUE TITLE
How to add a NRF24L01 to the board?

### ISSUE THREAD

**Issue by nldroid** [EasySensors/SwitchNode#4]
I probably didn't look very well when i ordered the board. I was in the understanding that all mysensor sensors worked with the NRF24L01 protocol but it seems there are two radio options,

I enabled the option in the sketch and then the switch complains that it cannot initialize the radio. It seems that i need to add a NRF24L01 and i see that you have a 'footprint' for it. I tried finding a place where i would be able to add one but i can't seem to find one.

Or maybe there's another option:

I have two sensebender micro's running with a NRF24L01 and they connect to a Raspberry pi gateway with a NRF24L01. Is there a way that i combine sensors with the NRF24L01 and the RFM69 in one gateway?

B.t.w. when i try to compile the sketch for the RFM69, i get this error: 

`switchNode:56: error: 'RF69_433MHZ' was not declared in this scope`

**Comment by nldroid** [comment]
To answer one of my own questions: You can have two gateways but you need to put them on seperate machines. I've ordered a RFM69 that i can put on a spare Wemo mini.

**Comment by yurysvirida** [comment]
Hi,

re:
I tried finding a place where i would be able to add one but i can't seem to find one.

the footprint is under RFM 69 unfortunately. 
![](https://raw.githubusercontent.com/EasySensors/SwitchNodeNRF/master/pics/switchNodeNRF.jpg)

do you have  spare SMD NRF 24 L01+ module? 

re:
switchNode:56: error: 'RF69_433MHZ' was not declared in this scope

I guess you have mySensors 2.3, in this case RFM frequency should be defined as following
#define MY_RFM69_FREQUENCY   RFM69_433MHZ

re:
2 gateways 

you can have 2 mysensors gateways (one RFM one NRF24) on one raspberry PI but my experience was not very stable. Although it was more than a year ago.

**Comment by nldroid** [comment]
Thanks for your quick response.

I don't have a spare **SMD** NRF 24 L01+ module. I have some 'regular' modules.

I'll just wait for my RFM69 module to arrive and create a new gateway with that.
